### ISSUE TITLE
Make color schemes rely on helper functions

### ISSUE THREAD

**Issue by SlyPuffin** [SlyPuffin/gyrifier-app#8]

**Comment by SlyPuffin** [comment]
Color palette defined here:
https://github.com/SlyPuffin/gyrifier-app/blob/main/tailwind.config.js

First color palette from here:
https://venngage.com/blog/blue-color-palettes/#7

**Comment by tliebert** [comment]
Is what we have now close to what you were thinking about this, or were you envisioning being able to pick your own colors with this?

**Comment by SlyPuffin** [comment]
Yeah! I'll close this!
